### ISSUE TITLE
Diseñar vista de listado del consumidor al seleccionar producto

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#16]
Como usuario consumidor, quiero que, al seleccionar un producto desde el mapa, se muestre una lista de productores que ofrecen el producto en cuestión

- [x] Diseñar la vista de listado de productores dentro del rango de búsqueda del mapa que ofrecen el producto seleccionado
- [x] En el listado debe aparecer información como foto, nombre del productor y reviews (puntuación)
- [x] Al entrar en el detalle del productor, debo poder ver el listado de productos que ofrece, esto redireccionará a la vista descrita en la tarea "Diseñar vista de listado del consumidor al seleccionar productor"
- [x] Compartir diseño con desarrollo

**Comment by victormolla14** [comment]
Buenas @Jov-co ! Cómo llevas esta tarea? 😁

**Comment by Jov-co** [comment]
Listo!
