### ISSUE TITLE
Diseñar vista de listado del consumidor al seleccionar productor

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#17]
Como usuario consumidor, quiero ver un listado de los productos que ofrece el productor que he seleccionado desde el mapa principal

- [x] Diseñar listado con información del productor seleccionado y listado de productos que ofrece junto a su descripción, foto y precio
- [x] Desde el listado de productos, debo poder seleccionar cantidad a comprar y un botón flotante para confirmar la compra
- [x] Al confirmar, debe aparecer una modal con el detalle, al aceptar, se debe abrir un chat con el productor que vende el producto con los detalles de la compra
- [x] Compartir con desarrollo

**Comment by victormolla14** [comment]
Buenas @Jov-co ! Cómo llevas esta tarea? 😁

**Comment by Jov-co** [comment]
Ya está completo 😄
