### ISSUE TITLE
Crear proyecto base y subirlo al repositorio

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#18]
Como desarrollador, quiero tener el proyecto base de react native alojado en un repositorio para compartir con mi equipo y poder trabajar usando git a través de la estrategia gitflow

- [x] Generar proyecto react native
- [x] Solicitar acceso a repositorio en github de Open Bootcamp
- [x] Subir proyecto base a rama master
- [x] Crear rama develop partiendo de master

**Comment by victormolla14** [comment]
Buenas! Veo que esta tarea está completada, puede ser?

**Comment by GermanCuevas** [comment]
Si Victor ! Perdon, me estoy acostumbrando a las funcionalidades del github.

**Comment by MCB-ONE** [comment]
Hola, soy Toni uno de los team Leaders del proyecto, @GermanCuevas podrías saludar en el servidor de discord https://discord.com/channels/892329434953170974/1004654155782160385 para saber quien eres en el server y poder contactar contigo. Gracias!
