### ISSUE TITLE
Definir estándares de código a tener en cuenta por el equipo

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#22]
Como desarrollador, quiero definir los estándares a nivel de código y configurar linters y formatters automáticos para compartir los archivos de configuración con mi equipo de desarrollo

- [x] Definir estándares de código
- [x] Configurar linters y formatters en base a estándares definidos
- [x] Definir y estandarizar directorio y manejo de imágenes en assets
- [x] Definir y estandarizar uso y guardado de fuentes en assets

**Comment by victormolla14** [comment]
Buenas @memoadian ! Cómo llevas esta tarea? 😁

**Comment by GermanCuevas** [comment]
Hola ! 
La branch ya se me mergeo. 
Lo unico diferente a lo pensado es que se mantendran dos archivos de tipo font , ya que ambos se estan usando.
Quizas en una proxima revision podremos solo usar uno. Saludos !
