### ISSUE TITLE
Revisar modelo BD

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#23]
Como desarrollador, quiero revisar el modelo inicial de la base de datos para identificar potenciales cambios y entender las relaciones entre las entidades propuestas

- [x] Revisar modelo de BD 
- [x] Modificar modelo de BD si se ha detectado la necesidad

**Comment by PinoFlores** [comment]
Los cambias son sobre el user: se agregaran dos propiedades para geo localizar al usario: `lat` y `lng`. Esto puede que en el futuro cambie a una sola propiedad, lo cual sera un refactoring en una sola entidad y solo en el back de momento. De momento para esta primera iteracion es funcinal.

**Comment by lexmartez** [comment]
Buenos dias Jose, si está completada la tarea, la cerramos.
