### ISSUE TITLE
Definir estándares de código al tener en cuenta por el equipo

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#26]
Como desarrollador, quiero definir y compartir con mi equipo estándares de código a través de archivos de configuración de linters y formatters

- [x] Definir estándares de código a seguir por el equipo
- [x] Configurar linters y formatters a usar
- [x] Exportar y subir archivos de configuración necesarios al repositorio

**Comment by PinoFlores** [comment]
@david-mg-dev creo que tu ya hicistes esto, no? En el proyecto veo que estan los linters y el format. Creo que esta issue la puedes marcar como completada segun veo.

**Comment by david-mg-dev** [comment]
Correcto, la dejo como completada.
