### ISSUE TITLE
Maquetar slider inicial

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#30]
Como usuario, al entrar en la plataforma, quiero ver un slide inicial que me muestre un resumen de lo que puedo hacer con la app

Referencia de diseño: https://www.figma.com/file/4KtdLLy9rZZxrRaPgNWW5X/KM-0?node-id=13%3A3629

- [x] Maquetar y agregar splash screen inicial
- [x] Agregar slide inicial con textos 
- [x] Controlar que el slide inicial se muestre solo la primera vez que el usuario entre en la app

**Comment by victormolla14** [comment]
Buenas @JTuyuc7 ! Cómo llevas esta tarea? 😁

**Comment by JTuyuc7** [comment]
Hola Victor, el PR ya lo tengo solo falta hacer el merge a dev, que es lo
que estoy esperando que se haga, tengo entendido que no lo hacemos los devs.

Lo probe en mi dispositivo físico y va bien, muestra los sliders y si ya es
segunda vez, muestra solo una pantalla con un mensaje de login, porque aun
no hay ninguna branch mergeada a dev como para hacer las navegaciones
correspondientes.

Cabe resaltar que el dispositivo que tengo es un Galaxy A72 en IOS no lo he
probado, no cuento con ese tipo de equipos.

Te acabo de taguear para que puedas revisar el PR y me comentas qué te
parece o si hay algo que cambiar.

saludos.

**Comment by JTuyuc7** [comment]
Tarea terminada, si se necesita algo, se puede reabrir.
