### ISSUE TITLE
Maquetar vista de inicio

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#31]
Como usuario, al entrar a la app, quiero ver las opciones de inicio en una vista que me permita iniciar sesión o registrarme en la plataforma, así como recuperar mi contraseña e iniciar sesión con mi cuenta de Google

Referencia de diseño: https://www.figma.com/file/4KtdLLy9rZZxrRaPgNWW5X/KM-0?node-id=13%3A3629

- [x] Crear ruta, página y componentes de la vista inicial
- [x] Configurar página como ruta/vista principal siempre que el usuario no tenga una sesión iniciada
- [x] Añadir formulario y validaciones pertinentes
- [x] Añadir opciones de inicio/registro

**Comment by victormolla14** [comment]
Buenas @valen-ruggieri! Cómo llevas esta tarea? 😁

**Comment by valen-ruggieri** [comment]
Hola Victor ya terminé la tarea, estoy esperando la Review de alguno de los
tutores
