### ISSUE TITLE
Maquetar vista inicial de registro

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#32]
Como usuario, al registrarme con mis datos en la plataforma, quiero disponer de las opciones para registrarme como productor y como comprador 

Referencia de diseño: https://www.figma.com/file/4KtdLLy9rZZxrRaPgNWW5X/KM-0?node-id=13%3A3629

- [x] Agregar ruta, página y componentes necesarios 
- [x] Maquetar opciones para tipos de registro en la plataforma 
- [x] Almacenar la opción seleccionada por el usuario para redireccionar a un flujo de pasos u otro según sea el caso

**Comment by juangalarza** [comment]
Ahi estamos batallando... Leyendo documentación y aprendiendo... En unas horas más hago un PR
