### ISSUE TITLE
Maquetar flujo de registro para usuario productor

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#33]
Como usuario, al registrarme y seleccionar perfil de productor, quiero iniciar el flujo de registro por pasos en la plataforma para ingresar la información necesaria de mi perfil

![image](https://user-images.githubusercontent.com/3885211/186196045-aad7936e-830c-4eb9-8f17-01256cee8105.png)

![image](https://user-images.githubusercontent.com/3885211/186196168-50e6503a-6d00-4271-bb16-8992bc74a8f6.png)

Referencia de diseño: https://www.figma.com/file/4KtdLLy9rZZxrRaPgNWW5X/KM-0?node-id=13%3A3629

- [x] Crear rutas, componentes y páginas necesarias primando la reutilización de elementos y contenedores
- [x] Crear formulario por pasos para el registro de usuario con perfil de productor 
- [x] Agregar validaciones pertinentes al formulario que impidan ir al siguiente paso si no se tiene toda la info necesaria en el paso actual
- [x] Agregar validaciones para caso erróneo de código de verificación de correo electrónico

**Comment by victormolla14** [comment]
Buenas @jmejiamu ! Cómo llevas esta tarea? 😁

**Comment by MCB-ONE** [comment]
Hola, soy Toni uno de los team Leaders del proyecto, @GermanCuevas podrías saludar en el servidor de discord https://discord.com/channels/892329434953170974/1004654155782160385 para saber quien eres en el server y poder contactar contigo. Gracias!

**Comment by GermanCuevas** [comment]
Las screens ya estan en mergeadas.
