### ISSUE TITLE
Maquetar formulario por pasos para registro de comprador

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#34]
Como usuario, al registrarme en la plataforma y haber elegido perfil de comprador, quiero ingresar al flujo de pasos para completar mi registro

![image](https://user-images.githubusercontent.com/3885211/186196261-7b146818-620c-49ff-812c-a743c48eed23.png)

Referencia de diseño: https://www.figma.com/file/4KtdLLy9rZZxrRaPgNWW5X/KM-0?node-id=13%3A3629

- [x] Crear rutas, páginas y componentes necesarios para el flujo de registros por paso teniendo en cuenta la reutilización de contenedores y otros elementos
- [x] Implementar validaciones en el formulario que impidan avanzar con el registro si no se ha incluido información necesaria
- [x] Sincronizar con el desarrollo del flujo de productor para estandarizar y centralizar las validaciones de formularios

**Comment by victormolla14** [comment]
Buenas @GermanCuevas ! Cómo llevas esta tarea? 😁

**Comment by GermanCuevas** [comment]
Hola Victor, esta lista la Pr, falta el merge.

**Comment by MCB-ONE** [comment]
Hola, soy Toni uno de los team Leaders del proyecto, @GermanCuevas podrías saludar en el servidor de discord https://discord.com/channels/892329434953170974/1004654155782160385 para saber quien eres en el server y poder contactar contigo. Gracias!

**Comment by GermanCuevas** [comment]
Vistas completadas
