### ISSUE TITLE
Crear CRUD y métodos de autenticación para usuarios

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#37]
Como desarrollador, necesito tener operaciones en la API para registrar, editar, eliminar y obtener data de un usuario, además, proporcionarle opciones como recuperar su contraseña y permitirle hacer consultas u operaciones de acuerdo a su nivel o estado de autenticación en la plataforma

- [x]  Crear modelo de usuarios (tomar en cuenta las relaciones)
- [x]  Crear ruta de usuarios para el CRUD
- [x]  Crear ruta de usuarios para recuperar contraseña y renovar token de acceso
- [x]  Crear controladores con operaciones CRUD usando los modelos creados
- [x]  Crear middlewares necesarios para verificar autenticación y dar acceso a consultar otros endpoints restringidos de la API
- [x]  Aplicar validaciones y casos de error
- [x]  Probar endpoints

**Comment by PinoFlores** [comment]
@david-mg-dev hacete un pull, ahora me puse a experimentar con los modelos para ir cogiendo el hilo del frame. Si te da conflicto acepta los combios actuales `current`. Aunque echale un ojo que ya me he creado la estructura de los controllers, routes, models, y demas.

**Comment by david-mg-dev** [comment]
Perfecto, estoy con los controladores. Gracias por avisar
