### ISSUE TITLE
Crear filtros y paginado para listado de productos

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#38]
Como desarrollador, quiero tener la posibilidad de filtrar por los distintos campos de la entidad de productos y sus entidades relacionadas, además, quiero poder paginar un listado aplicando o no cualquiera de estos filtros

- [x]  Definir filtros disponibles basándose en el diseño de la interfaz y los campos disponibles en el modelo de la BD
- [x]  Definir ruta y parámetros de filtrado
- [x]  Definir función en el controlador y handler para los distintos filtros y sus posibles combinaciones
- [x]  Definir parámetros de paginación y lógica de control de paginación en el controlador
- [x]  Probar endpoints

**Comment by PinoFlores** [comment]
## Documentacion

https://gelatinous-geometry-f62.notion.site/Productos-KM0-API-Documentation-67c4dbfee7fa42e9a4d946fb64f78ef8

**Comment by lexmartez** [comment]
Si está completada la issue, la marcamos como completada.
