### ISSUE TITLE
Maquetar vista home para productor

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#45]
Como usuario productor, quiero poder ver la vista principal de la app tras iniciar sesión

![image](https://user-images.githubusercontent.com/3885211/186196457-5cf021dd-fb58-4bf0-b23f-2d4c6142ef1e.png)

Referencia de diseño: https://www.figma.com/file/4KtdLLy9rZZxrRaPgNWW5X/KM-0?node-id=13%3A3629

- [x] Maquetar contenedor principal de app considerando header, nav, botón flotante y botón de notificaciones
- [x] Crear componente para mostrar opciones de calendario y reviews 
- [x] Crear componente para mostrar listado de productos asociados al productor
- [x] Crear nav principal con opciones de inicio, chat, productos y perfil
- [x] Crear componente de botón flotante para asociar nuevo producto

**Comment by PinoFlores** [comment]
## Productor Data

![ProductProfile](https://user-images.githubusercontent.com/77801995/185783506-f89e54c7-eb77-408d-baed-d1092a643cdd.jpg)
