### ISSUE TITLE
Diseñar el markup principal de la app

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#5]
Como usuario, al iniciar sesión en la app debería poder navegar a través de ella, ver un header con la identificación de la app y tener un menú de navegación para poder ir a la vista que me interesa

- [x] Diseñar maqueta principal de la app con header, footer y menú de navegación
- [x] Si soy productor, la navegación debe tener enlaces a la vista de perfil, mis mensajes, mi calendario de entregas, mis reviews y a la vista principal desde donde puedo ver el listado de productos para poder asociarlos a mi perfil
- [x] Si soy comprador, la navegación debe tener enlaces a la vista de perfil, mis mensajes, mi calendario, mis reviews y a la vista principal con el mapa desde donde puedo ver productos cerca de mi ubicación
- [x] En el markup, debería poder ver un listado de notificaciones para saber cuándo tengo un mensaje nuevo en la plataforma
- [ ] Compartir diseño con desarrollo

**Comment by Jov-co** [comment]
Las reviews del comprador las voy a ingresar en el perfil del mismo, para ser más administrable, ya que quizás no es un dato de relevancia para este.
