### ISSUE TITLE
Desarrollar header común para vistas de comprador

### ISSUE THREAD

**Issue by pedrovelasquez9** [Open-Bootcamp/productos-km0#77]
Como usuario, quiero poder visualizar un header con las opciones según la vista que estoy consultando y que me permita cambiar entre el tipo de vista de mapa a listado y de comprador a producto

![image](https://user-images.githubusercontent.com/3885211/187367096-4f3c322c-740e-4148-bfa6-1f5b568869e9.png)

- [x] Crear y maquetar componente reutilizable
- [x] Agregar enlaces para poder navegar entre vistas
- [x] Parametrizar las opciones que se muestran en el header según la vista actual para indicar la modalidad activa (enlace verde y enlace blanco)
- [x] Agregar header a layout interno de app
- [x] Pruebas funcionales

**Comment by JTuyuc7** [comment]
@pedrovelasquez9  @MCB-ONE  me surgen unas dudas en cuanto a la maquetacion del heder de los componentes.

![imagen](https://user-images.githubusercontent.com/50525507/187525845-f5e6d590-e247-4d7f-a15a-5b305be10348.png)

especificamente, esa parte.

¿El boton de la izquierda cual es su funcion? si tuviera una funcion.
¿Es una lista scrollable? si ese fuera el caso, cuales son los demas campos a mostrar?
¿Se muestran condicionalmente?
¿Los elementos se pueden seleccionar y/o resaltar?
¿De tener la opcion de ser presionables, que comportamiento o ventana tiene que abrir cada uno?

Gracias por las respuestas.

**Comment by JTuyuc7** [comment]
@pedrovelasquez9  @MCB-ONE  

El comportamiento acual es el siguiente, si embargo la lista que se muestra debajo del buscador, es una lista dinamica? o cual es el comportamiento para ese componente de filtro?

https://user-images.githubusercontent.com/50525507/187536017-7bfa5855-a75b-41b2-82e1-e04a19394bf0.mp4

**Comment by pedrovelasquez9** [comment]
@JTuyuc7 

-¿El boton de la izquierda cual es su funcion? si tuviera una funcion.
según el diseño, entiendo que la lista de filtros son accesos directos que el usuario podría configurar con el primer botón de la izquierda, sin embargo, no tenemos diseño para la modal de configuración, de momento podemos dejarlo en la maqueta manteniendo los que ya se tienen funcionando.

-¿Es una lista scrollable? si ese fuera el caso, cuales son los demas campos a mostrar?
La opción "ordenar" debería abrir esta modal:

![image](https://user-images.githubusercontent.com/3885211/187931972-a92a06b6-f928-4271-891d-f0fea039c208.png)

-¿Se muestran condicionalmente?
Los botones son parametrizables según estés consultando productos o productores, ya que puedes ordenar/filtrar por características distintas ej mejor valorado (productor), menor precio (producto):

![image](https://user-images.githubusercontent.com/3885211/187932147-b044b7bf-a245-4c5d-8a1b-e64ce6fcf6f8.png)

-¿Los elementos se pueden seleccionar y/o resaltar?
Los elementos no son combinables en principio, solo aplican el filtrado/ordenación a manera de acceso rápido

-¿De tener la opcion de ser presionables, que comportamiento o ventana tiene que abrir cada uno?
Solo la opción de ordenar abre la modal, el resto actualiza el listado consultado aplicando el filtro/ordenado seleccionado
